name: gerar cobertura de teste
on: [push]

env:
  CAMINHO_PROJETO_TESTES: ./SistemaVendas.UnitTests
  COVERAGE: 0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Code Coverage
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity detailed --collect:"XPlat Code Coverage" --settings **/runsettings.xml
    
    - name: Install ReportGenerator
      if: success()
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Gerar relatório de cobertura de testes com ReportGenerator
      if: success()
      run: reportgenerator "-reports:**/TestResults/**/coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
    
    - name: Criar diretório relatorioTestes
      run: mkdir relatorioTestes; mkdir relatorioTestes/reportCodeCoverage

    - name: Copiar arquivos do diretório ./coveragereport para relatorioTestes
      run: cp coveragereport/* relatorioTestes/reportCodeCoverage

    - name: Permição para shell script
      run: | 
        chmod +x checkPercentCoverage.sh
        env.COVERAGE=`./checkPercentCoverage.sh`

    - name: Upload como Artifact dos Reports de Resultado de Testes Executados com Sucesso + Cobertura de Código
      env:
        CAMINHO_RESULTADO_TESTES: ./relatorioTestes
      
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: reportCodeCoverage-${{ env.COVERAGE }}%
        path: ${{ env.CAMINHO_RESULTADO_TESTES }}
        retention-days: 30
    
    - name: Upload como Artifact do Report de Testes com Falhas
      uses: actions/upload-artifact@v3
      if: failure()
      env:
        CAMINHO_RELATORIO_ERROS: ${{ env.CAMINHO_PROJETO_TESTES }}/TestResults/resultado-testes.html
      with:
        name: resultado-erros-testes
        path: ${{ env.CAMINHO_RELATORIO_ERROS }}
        retention-days: 30
